apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:629BI5oQcUcK0D9SSAmGrp5FyhA5XboYjGycCoRw+T72jBkc83lAjATOp2MlXE6Yb//BMMqh15wcviHdmOMqtaA=,iv:nW8vbAlPViKhrUIojDecVvHe1FSBz3znKi0V3mRRAcc=,tag:a8znySnKBHJPzjrCzQSauA==,type:comment]
    #ENC[AES256_GCM,data:p6qUTys2JWaFvEXaR1pvHqqgkN5o89vq7peWszWkVv01nHObcgQ7Tcjh8sc=,iv:fKQGwiY2x90450ylbPh1529brrKgcA2vua0EKOT5zUw=,tag:vrt9XURc+A+I2QRj4H/xiw==,type:comment]
    VIP: ENC[AES256_GCM,data:Utmraz392r3LgKLzkA==,iv:M0dyGjqm93k6atgy9JVxjonB5KiCI1f/bqH7SjdvMNw=,tag:+PCXfw39SMVX8uKtqtIQhg==,type:str]
    #ENC[AES256_GCM,data:h3k0zkfQxZOSpmUz5sYAAiEcPbn4Y9FEELk=,iv:ZQ7C4cI9o+DAF5cj6d0BIFgLCtA2CTq0EkeSjb7F/EQ=,tag:eQdXXeV3nK0828t7aobaxA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:I48wjR+YvJkKBtLVXoc=,iv:Iwr62zqSYgALqRZZSTQqyVTC4g58X+yVJXwhL5tLXMg=,tag:7x2KLUFYyuGwlyyb7UWr9g==,type:str]
    #ENC[AES256_GCM,data:sTdkvZ3XvVV8cTFAIf6Kc0gKsNQmaySU5LTpE6gnJAPorQ==,iv:4qRqOx51WuK8wWqkRiDIvaW2hmPw54k6h7eykjKf7eI=,tag:59uLSpiDTyRs2vratW08gw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:gjYy6e2kAPN+xxeX,iv:AdxMJT7o0tSTukwfJXwlZZx/BA0anEdOqBYd43AsoCw=,tag:vvyjaho5CK6K3yZte6rw9w==,type:str]
    #ENC[AES256_GCM,data:Xkhs6uaAM+eXX2jRNr5X5J8ZCExz+Rk5KOEOvtCfA+Kwvyo6BTUCaa3am4Wn1cM=,iv:CF/RB8Bij6HJNlvx41P/smakAbr/99XLIFzeMnzee6s=,tag:2R1F8ibRVJw1nuNprVsWhw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:HdRpCKoUgWtBpILx9hKlYduOZQlMK00cXycE,iv:90CAvd74r4GvuzbYpOApzZic/JowF6jTr2A1zYzqaUE=,tag:vL88P3t4zideVHjCO8E0Ow==,type:str]
    #ENC[AES256_GCM,data:5Fzr+0zzLNxUpG5Ybf338Nlf2gwW1SWqtqxbap3HjutwjF/H0YNHTxLdsijHJIqQc6IDbwKewf/5/NOfj1cBB/DBRF9d+YIPrmc1cUIxNAU=,iv:69rA3x2+1A34yH2VSqfWFtrFd1hJg0iTIFztyPTvthA=,tag:LbVzT3PP98tNADLxV8u8EQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:9mIwbPaI6b6zH9suCg==,iv:am9bXbD4ICxX6MXmduQpz44/C2X+wf/zcY1d2GVFQz0=,tag:cikryeiMhSQSD3VB2f44Lw==,type:str]
    #ENC[AES256_GCM,data:8rVuHdpHwK4KJpLeuqwv1C1BMNSfaCPukYLrmwca7u9ULmpP1yOFD5aiWw4N8drdM2PbUBB5FrQ=,iv:F2iuIUSl76C57rcMnsco8U1+7gb3GgaPiLCVb7LRGJQ=,tag:gZTwpCp9fu89kKs6k9ejQA==,type:comment]
    #ENC[AES256_GCM,data:pAq/3//+CO8oOND0qQFddM/TuCcnahRkKA==,iv:cwN5XpGIFvgnQ7X0KMqKDWPXNYTLr+LG0TI4v4HZFAw=,tag:lGE6xxzfI8F7VCkkuToR4g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:CeQ2DFIKou2XljMLBMwivEI/3VCMp9HGhSz7Hm2wEL11JlucvRN1hLi36CGiJOs=,iv:TTvtjbxbagyOEeq9mhBozQltZHgt2fIGLq4mumvXfy0=,tag:sNcP6N4E7Rj/b2ZXJ1FLXw==,type:str]
    #ENC[AES256_GCM,data:g3uvDz9lTq2VWu7J8ntXnLY2+W94zPtHqbpJo9oTh1aFi2IJGtZ152pQf8O5cdNm0CpSqfL6SL8bU++PUuBtJv1cIv/x6iI=,iv:YE4s8kB8FNFbGmAcDP6954T+W2x4tT125MNlZq9k+20=,tag:pV6jQN+ZKivV27KzBaXfrQ==,type:comment]
    #ENC[AES256_GCM,data:Pm46DEPGXtU/qSadNVdwP9QGHUDserPNqpOOManMqC1fs21j/gsYdiSFr8hZRAheAQO48d4k,iv:l40Qnk9dFaKxq/IeNUbVLdlyI4I/KTapYuq1oduRA4Q=,tag:7GVn+s0ZG8HiM7BRPC13sQ==,type:comment]
    #ENC[AES256_GCM,data:MdKT7eyoA6olq/ayv0jgryc3gFdfsA46fyuIrgF1Jo13qwY=,iv:+IZqFSC/doGN9M4VMmaGMdVYQepJ28NwnnH2RX91gVQ=,tag:SDIa1mY0FRsP/sgme3vExw==,type:comment]
    #ENC[AES256_GCM,data:2EjIaqXSr9FdoTbzf6AtaP2CZ7vDPypvS5OX1CaNALu3khe6Qo8E,iv:X69Pi9+BSMgPQPaUi6tdzMSAJ+3GwZPfYa5r978hO8Y=,tag:IxPi6D6QpYwr5BvM3CwcJA==,type:comment]
    #ENC[AES256_GCM,data:1Qb8nUjVYwDcpvbuTyU=,iv:1mobcEBhUGLltXfXaDP7hbo0GNCVYTEa6dW14E6e90Y=,tag:9hEwtit8vCunNEFAfTccfw==,type:comment]
    PODNET: ENC[AES256_GCM,data:iSoSCNgzqd1kjxjlhg==,iv:LwlEBGJoWverE+gOmgCACzxfrvjwh4vs0n+2wYc7OR4=,tag:YB1QYXi9IAiBgd0VS63uqA==,type:str]
    SVCNET: ENC[AES256_GCM,data:yd0r9oNGjj5a/JmSGQ==,iv:Hk+QPl9jSdys0QHYX6G9wUNj/+alqH4gxWC+Sx7SDBE=,tag:ioL3D4ZVPegIc3n4RI3pdA==,type:str]
    #ENC[AES256_GCM,data:/eaATyzHHHdLAw==,iv:g61DMFm7qd5o53ekBL2RC6rPKCubHJGBMn+FqT6c7Bs=,tag:fp6cGdsPX56ndPMsp+cvxg==,type:comment]
    #ENC[AES256_GCM,data:Zltmp1v1NVA=,iv:st7rzipr3qfZiMAeNp6YmYQIx4DFnfsQpQ/58P+oyXo=,tag:A9uwweG1bknNCa9kcEZdzg==,type:comment]
    #ENC[AES256_GCM,data:porL1a1i5wnNF77fud1CWJwBxUQIl43eMA==,iv:+/Fndbshr4YxOv/rIoiCKh+p1J2zvJl3TDkHEuxBePg=,tag:7dGkStzEDaATiCpxNLHuxw==,type:comment]
    #ENC[AES256_GCM,data:FHiGo2HbTA13aw==,iv:j715M88cmUYwnZvgxLfh5gOjceuGEA+pZFasM2yDDB0=,tag:KXCeNiyNizeRUbw7R6LKtQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:DUy/qeQnSHcSi7bOsA==,iv:mUORThD4RiBNm9Z/oCJogbnaq5z0gB0utUpqrRCoZCk=,tag:a7v+4XglD7lPeg/3HK4wHg==,type:str]
    HA_IP: ENC[AES256_GCM,data:Qt/bDs01He9gS4BCww==,iv:Gc5HJLZbHKNqTE0uERf2sCSLkgd9lvyEWN83EkDZ1tU=,tag:6rWEmsV5zs5oYayH+cjXHg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:+eUuL4jEDpJs3ELleg==,iv:3vgZjIG3LXl3oVcfd6YYAUo4zpVcE26OIHuQUg3ZhT8=,tag:sKmQLkz8P4Ouj7BFE3quXg==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:viYBXE/ice/ONf/DQC8=,iv:Y6Q3ehqvmHdWWghMBlEfY2OPTEDDZeSkRMMkUyMRz4E=,tag:kQOqNpzV+GDuKXyJCXzv5w==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:CuYQgQRdanLO3Dwt2cU=,iv:6epnCqUQY/b8tdz1eBZoP6GD3kqPNQ5XgTYgnJdspR0=,tag:rSsWWuzIk0wfMta+sS7erA==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:J9ajx1RFn/sbR5kZBuE=,iv:4Vmu8uIBEmL19qa4oGI3YccCWM/h32Gva5DyO8x7RtE=,tag:C10g2Ru2k3YHGjJ1Gsw3xg==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:uwCeFls30BJhzX7sTg==,iv:gPNeqOSDwwWD/PMGljS5bVK3Jhzs/wUDFL5zd6aumhg=,tag:U4yC9+EjtthyB5BiagG/PA==,type:str]
    HASS_IP: ENC[AES256_GCM,data:wU9VDU33PuyOwqJSyQ==,iv:EsEpjFO1lQg3qNuK1tmWNDo0LE14fij5BRIF17ncgno=,tag:gSd1r0Du9w6kZ2/rD/yP0Q==,type:str]
    #ENC[AES256_GCM,data:e40fWJFQ,iv:PjS8ifbOucFKaSaZCW/j5zGtfesBM3T5jja4HJXh7XU=,tag:PWnkwKm7An6tfvujPSykhA==,type:comment]
    EMAIL: ENC[AES256_GCM,data:q8tnMMGd44JH/JgG1OUi3dWjcDDWdK30mOPqSjNaRg==,iv:rVc+rHJMHtnXulbTc3SKAtQPLyd0Ug/cCgn44WjC/x0=,tag:FZp9lNPd0btyQxDc1ZqrRQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:90CpCIBIOrwvD1uUMaKST6P3zgzasUHXMB/O7nJZ+acj7l62z9eMQQ==,iv:VrSmCRSt764hq9Mjpx89Eo/OlN8bJo4neNZVuluraCw=,tag:5pfHuHlNKUC09R6wJLxkIQ==,type:str]
    S3URL: ENC[AES256_GCM,data:1HsXUooaVTadZJLfEVHD/b95IKGeFvSH2uzFIxXq,iv:fiAAdhfjPXI/uyNTmV7pIsjhNv7oaVOivfFSC8ydR+Y=,tag:UhBPm8gf2PJXc78LiNqmcw==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:ZErqQxoazAjIZauX3g==,iv:n2xNa6txl3yqERs7Oi7YowAQ7HpinGZrN4VgxdU/DIw=,tag:bDzPJORF6VGw6vSSFtsBZA==,type:str]
    S3ID: ENC[AES256_GCM,data:XpvzeAvaIQfzdrA2,iv:/ne8M7mDcJG1YkY54favcbaQ2p7UYx5kGPN6SLuCjJ0=,tag:jkREpBtIAENBSGNWTPx3sA==,type:str]
    S3KEY: ENC[AES256_GCM,data:Za4ACM93Jz3wNrA74L/ymSUbpNxiS82h+e+89Fvo3hDOPwhmS9nQlUVV,iv:eKjtY6O+DbPRv23p2yGqs890B7mIA6FCswn2PkyD4RQ=,tag:ZqjDHzf6z+lq12MEOOj44Q==,type:str]
    #ENC[AES256_GCM,data:a5uEmuM88E8=,iv:1yYhs76OL8CU9TVzXJqVZbZU29hHJJdmVKixQa61x1k=,tag:wW0ZurDFgbICvoYf6FdQxA==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:MkrK9og4NUKIvXFDlA==,iv:3pPF+gXWgkiVlOg6WYyvP2VL2PuohfOKSOTYkHuN2l8=,tag:9oxcTUY3ZgltFZboEyHl7w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:6r1A5A==,iv:Dxl8DBEqJ+YButXrZZkBc2iZFaCuhTQNX+gX4E7Rp5M=,tag:Kx8geKadyv0t9FKQW+yMzg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s36l3k7xz668jyqa6200me5tx7xg2nzs0ew6rzp05cjnmvl6kpqscc2frq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTFlsWU1abzNBamlGbW1N
            K1RQbHQ2MHdRa0c0bU93WnNJMlRBdlRFa0Y4Clg5SDkvd2t1VXpFaGIxNW1rbk5l
            bUpRMjBFdkRhd1VxZHJVY1RzNWFxS2cKLS0tIEltNmNxeGVtM1M1c2tUWUcwQWlo
            S2t3RmNEeFdiNnppazVkdzlrRG02cGsKo4olSYi8i9X/DXSTGtNooOdU7jeUkKKM
            O0oxFd/uFuqCwgimx22XbtVWFo/W55RcOSi/mw8ojYCBKhZEitr9mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T19:18:58Z"
    mac: ENC[AES256_GCM,data:a1TB+DQrijF390a6X3tMCdWOl9xAfV+iZ0fK/lR8YIg7yNE/gewaddwkIQRawV5A6V/ryiDKiISZlohVi21GmZuAXZzycwrndknb7LfNmSfYGcM9/30kcyv9o+rX9qTBit/FRynbxp2K9rA6InuhzRQn4fxdisKcJSZheI6WVV8=,iv:gtO2GzgPEd/HZL8vYhYwxNLgk6LHLbSHyvd0qkFB9J4=,tag:hFtsVfIFxcaPQ4mprGG4bQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
