apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:6qWzoqDttF+N+EaGb9jDE0zAyxfTcHXyB/DjurTKHlxcgkNvf2FLj0/b9dRdXU6Pqs+entqu1TiSz4ZLq4zHxPM=,iv:1oyxWvfeVGmeXk7C/E+/A87nBHY0TDlG7now1C+RJyU=,tag:ck5rfm12aC4qqbeeG93q7A==,type:comment]
    #ENC[AES256_GCM,data:YLGlnRHCl7rjwvgP+tQiF3iCooHilRjjpVPMzqGriyVD0yyfu+kOm0mPonY=,iv:8yS+B6r6/jgJKp+veyoSa/5E43Dp+MsfOHQyveB/iPM=,tag:Bnp7Dm38aFix2Bm50d8l8g==,type:comment]
    VIP: ENC[AES256_GCM,data:CTJCjp8phir4V7DAPw==,iv:p3U8Rc2HOuwQtxbTYMNk6Z/8UdX7XAcelSAzpIVGAO0=,tag:Q4gWDHFaCF+pRG1SuGliMA==,type:str]
    #ENC[AES256_GCM,data:6+w0EPqcI5SR7A8kwcPlbNtjX7kHBlgwapY=,iv:wwaFeGEG14eAMBz4QgNRrvf8xWQ+zx5f0itb/q3cIng=,tag:NJrcwADlqJ6GoSXu4KAmEw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:Qa1UstUzj7NrI2FPDwI=,iv:YAukxtUdSpiIiY/WQtjjXgnlKZVieD8uMpfX/WyrSmg=,tag:V0elNOEPc4kJF9qCFzZ0Kg==,type:str]
    #ENC[AES256_GCM,data:Fvt3/MI0fWLPxIB99/6gf5aKIdZcrUhPjXSpv/p1UQ6DLg==,iv:2SS7WnScGao+R8zXT8kDwp5FYxnAaSW7Rknktyt9vMI=,tag:7AUtriib9ZvLMafd8/502Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:YGR4tlFXnD0lcGbd,iv:0RM/7E6d2tzKwtOPoNoaE3m6dj2ulFXxbUxuY48Je9k=,tag:ikLp4GDgw6ifZA8l+k4noA==,type:str]
    #ENC[AES256_GCM,data:yHErvvsS1nkFK8vnxJQm2N8kd7hnAU8Eca9QkRyZQfHLuXRe5XSffDcmKKoLVMg=,iv:pnnHw2r2swwcBELBlYR/UUONcKaVre8a2qfERdAMCbI=,tag:+g26U8k8tzZbAlUslcDnag==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:Eh4K+vhjsjuc7GfItVqks5oDWOXgVXyaiiU8,iv:fMpkg6RS4EQQzEKT7EqMxbO488sEvIkyiVZmI/AfVPM=,tag:bZ/c+o+sTbV6Z1Ym6AqngA==,type:str]
    #ENC[AES256_GCM,data:gZpbSuUsh+x6ZkQ2RXWvzS0tTjA/hyPM4Bxfj429A4AO/qchfnz38AH8zO79I5oYUpVXDoOq98LjpnnZFJj9CvJT0zNn21/4AUK0znH3ojg=,iv:u1DVR7zQkiKJI+pBwOsCHYHCUcNQZ693MIczoX6kRTU=,tag:zxwzU9LcuoO5/kNKbxAvSA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:eJQsSHkdoMxcMzW4Zg==,iv:Ks4E+2PrVu0vlJSglQgdJMENKjhWHkG0hGfviVqqEsY=,tag:D+Uk4AH47YAXyzZloCXOYw==,type:str]
    #ENC[AES256_GCM,data:ENA6UtUk9LgicHZxGVgDUQ+rwPdoaYS8P0VUAKX7erPboCZWoU3zk3pE7iROHS4BYdgiysGCU24=,iv:VyGUu0lb16zedZxiuYvVRe0YxnADF30D0wM9i9bI7i4=,tag:vTuomQf9j8UNvp8mZybZGA==,type:comment]
    #ENC[AES256_GCM,data:69S59MpT1i5o8JUuo6Re/q3AW8/Mwio43g==,iv:zFdv6VplbLB5QMu6zKiaKxfxSs2CYnApN/zWiuYiGUU=,tag:TMm8wPfd7g5T/+VjAdTXUA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:qEzgKxqZC1INLPvz1mVBMiDtIOpmWsb3hVcJi54/xRqmn5kspkJDznU0ez5bA50=,iv:eWQVzGD6oYG9wqT94UA8Yq8DwSyfwpIRTvHrkY05/RQ=,tag:PGpqniNgnQSlccc/LWheTw==,type:str]
    #ENC[AES256_GCM,data:5MJ3iSmQAcU83nggXmKI2qieDuptFmMxTueTZvNm6v/RlBWIWctxITMcnXMAgrmzkEY1VufcBz8m2a7KYYYi8yPzzy9kBUs=,iv:Fv3958W+vObZELal5+mxMTUSQp2lAzU610uFAmkfmgk=,tag:wZZiMhPtocjLQVqP6dEKKw==,type:comment]
    #ENC[AES256_GCM,data:A3PIs7RgXrMHTaemYr/ydMG6OJpn80D/e0vJap/U6OE4eo5ic3OWQq9NxL5BcIX+NjndS6E1,iv:GLUWot/9uqi3M6FCMsLTNoiY+Boh/CFaEn/CQSyQIOY=,tag:JXThr8CnuO7kCLeVj9IGSg==,type:comment]
    #ENC[AES256_GCM,data:vRHjpOYH5ejKchiYUwW1+ku1xLKL3af33Y7oAYn+wjsZySE=,iv:jIMwKWl7Yy+K9PtMU8CGQzuI131kYkeMHySKaET7KBE=,tag:hiHUbwUr4zvXdaPQbc40pQ==,type:comment]
    #ENC[AES256_GCM,data:mxuRn95pORrTqiyWL7UJRGGQAXO9KJdu25isjXWnf2bhYvMPiCFA,iv:GeM94KbuOLgmhFyWXcllzFSZKKsBw0BhgpxYwb2u8/I=,tag:nzdK3QLHjVgWYYTzKzjBPw==,type:comment]
    #ENC[AES256_GCM,data:7v3aSHrDZwy/9pNfJOM=,iv:9fgpxtvQB1zUvXSa+6rBwXEJgITdKC1aCwJ7/rQde7c=,tag:s6yiZJg7HjUqtXARfAC3sQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:AAdDzatlcceEmwuvkg==,iv:IRgAVjuoV8KQj/5SlSWuITjWDj4hBr9ctVQ2QZ0KF8E=,tag:MZh206ZKu31Wvfi8Cbh+UA==,type:str]
    SVCNET: ENC[AES256_GCM,data:9xV2zFw/06ihML6w5A==,iv:HmYfE6ZJrpMWU+VIwGHLVl//4Da+OujnH1gMHddyNnA=,tag:zi2yI2uICvZztTA2M/1Hdw==,type:str]
    #ENC[AES256_GCM,data:Z/fNbi3NYeM2kA==,iv:1O6l7argNK9BKrJehZAGscRj9Zv/jNhBEc3ae0nWW6k=,tag:mli1HQ9FoEXSj+aqpgo20w==,type:comment]
    #ENC[AES256_GCM,data:MS2wL0ZOsXE=,iv:mcQaVnX+GdvwX1IXwYfdw56u2N6nm4ncToopdJrzhoM=,tag:WR3OUGrUfyXn9NV6dVzvKQ==,type:comment]
    #ENC[AES256_GCM,data:Gsum08YJM8e3bxpP9jKYkh8H7ab/ekts2w==,iv:ZPmWsTV3U+nfvQMNpIX9TbB4Em9SDTwWNyBOexP0bdY=,tag:JmxFTtdunlClHIO4W5hyig==,type:comment]
    #ENC[AES256_GCM,data:xo/+w3snLu85lQ==,iv:Xg+M0NwlRnmqx6wFAefrVDZnEe8AxcIrsUB88VqpkHg=,tag:EEzrCG8GRTMuAsskYRUp2w==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:OjoCDiW8EiGN8NZu1A==,iv:bPUSPuSP/xmsJ5TWNgNBDVwTgffbsgJWANDXFlg3O9A=,tag:2Ut28C+hwJQHwqAerIgt+A==,type:str]
    HA_IP: ENC[AES256_GCM,data:PluF/SPl6FT8umMxbw==,iv:DN4D222sgh39ozQB44/d8rc+L84Dg1DoWgaXWl8mlHg=,tag:qRCiilJkDwdc+WE3/0ULPQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:m1fKMYR51iSIdOSxOQ==,iv:cLSBx2F8nAWDmyIkxhyT/JFPGGjZAewQrW9tUs+GrLA=,tag:Oh6SVryoKFtFcyecBkcmRw==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:/QijqXVQCBJGqDXJ0NU=,iv:WnWmelC9nSw7bCzZGwEPFL8qdXvWQjkLl0uoEoszpo4=,tag:RWRxUOX3YCGL8CGugV2efg==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:OrH5AeljnIPLxR00j18=,iv:8Cli0xDAIbvCybhDvYxiWMc2iLla5hb/jyFfczv0wbs=,tag:gCHSjSQs0pE8+fkZZYJGgA==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:Kkq9MnBwMkF84YhUR5Q=,iv:+UntbltKKUqNk7P4fNcrP5+vB4RswCywAIzq/GjT3pw=,tag:FGTyrUW7Ntji2tYKiIEMwg==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:Rfh92+6j8UxeeOyasg==,iv:oTcSBkJqJh70g6oFMAKqgjn9AXd7T5zrjs7AcVb5RUc=,tag:hP3J98w/Fs3sGaoCmowk1A==,type:str]
    HASS_IP: ENC[AES256_GCM,data:iaI0ggb/puLdJb+iug==,iv:dgrjlnqhXjK7fn3Wm++7/d2qL0y71MgxUmx0+jjKIps=,tag:I5vKpXqBKhAoRfeVDC7LOw==,type:str]
    #ENC[AES256_GCM,data:3abiGp5H,iv:1kjZ2pRVtEYNhP5UdYbXGLB9/j47vs5JRJmOST3mfJ4=,tag:M1hG1eiuDsAhTytVM3lvXg==,type:comment]
    EMAIL: ENC[AES256_GCM,data:5HqU+xksaS2Vl8aMLrkG5DRXd/zLkJz4hKPZ441kHA==,iv:duCqC3OiwE8fnLlQldWQjJkfdQO8gZzJStnIvWfzXNs=,tag:YwgCMDp0zv2UmY84zc1FLw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:wFf0fOH/BkxoegdXF/zQf9HaebFzvbYNISlsqMyXfwBUHD4NJrBhRw==,iv:8NjlY2Li5ABUCo5v1n6Llbv5HVWkILOge3zSGHSVAG4=,tag:xC+gHaA8vljEwZpEnODgmA==,type:str]
    S3URL: ENC[AES256_GCM,data:7z/JgkHOWbjn7JonB6Z9i6c1vsnIGySjeQCd3HkO,iv:2pMTM6GVhJhSXE9Mb8xpOYM7A78rw0r8vo8YZCHwu6M=,tag:8wLk2ECIk2Ir9U8Bhz8Qrg==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:RwWLPkwOhg/vA0bi+g==,iv:9YWdibR3T2Hlq3Pyh+ESCYs7lpYLJzV3AcgmK0NnxfM=,tag:gwdT8qNd6PVM9dpXh1ZaZA==,type:str]
    S3ID: ENC[AES256_GCM,data:eMqTXFHrTVq/sRvF,iv:pNjGOB45UadCxP2Ukwbxkvck1AbCTr3Nr5MTJxaZOzs=,tag:HyWmamjAOAn42Yi7smRnrA==,type:str]
    S3KEY: ENC[AES256_GCM,data:a8RukZo5xvNiMmFQPswb4KCtmd/IV0x6BXMD5P8wdwNdaN5NT8ImVWJO,iv:WK02oh65yqtxDAW6VTzMDRwKv/GWgN752WVTDP61U8M=,tag:snuToEmV6OfS7sersYvhDQ==,type:str]
    #ENC[AES256_GCM,data:ksU5pUN35vs=,iv:1QOCFsadWWI0D/VZPtU77CXhaWQFffFiZ8Qgrtdiy44=,tag:qXgH+yOt+QCth8tD6kOHGg==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:3Z3StVe5CWP7/pUi2Q==,iv:gKTVdfYr0UUE8tXgf6ycM76mYG4sn63g6709pw88eKQ=,tag:m+6jyEMzKnu4HoXDCOzPKQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:nCF2qQ==,iv:Eo05agLHPoetzhbTPYPRdiJNOhX9t1b8cimmeFvMcus=,tag:Y7NhXTf0x4S082ipi3IiHg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s36l3k7xz668jyqa6200me5tx7xg2nzs0ew6rzp05cjnmvl6kpqscc2frq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcFZXYVloS210OU9LVk8v
            Q1M5N0Z4Tk9aNTNQVzh2RTRPeDB5djhGcVhBCnp0SEloR1F6c1ExZDRGQXZpUkxS
            SGNDSFNIQ08xM0R4U0NiWTdMR2ZRM0UKLS0tIHRuWTdVSnFiSzR5SzBZVmxUbDRq
            Zm5yaWV1MTJwNDlOVmVEaHZZaUlPWFkKpGwmfdCbVQtvwkwMeizYlr+cArvigolk
            aalK9kR8CNcMu6ptMhYQyJJEPngcLVkRnqIJklWKi1xt2hAKWR9zCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T22:12:19Z"
    mac: ENC[AES256_GCM,data:MyRLPO5eqINhe80BRxxpd3fFL2pE9IgzYAy0n/ez2i5UqIMY5JefpeYOdeJZR8lUhzxB2z/g0CsrKzCCf8qonq3fWfqaCNrvKWJaKiwXH6zGWW3T7QSRDwy5qRhaEsCp+YgftdCT9/U+wgTZVDUl6grSSS3gNbgOZd1WLOhFN08=,iv:1SDy4+UV1cLCg8qvUrk0jZ4jO4zn6oGfAJfcMKvhmXU=,tag:DP93y3Gvxpg19/rdgI+DHg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
