apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:jWL/L5buPRcQFdSX9sW8I7IcinPDJvQHq5BEKZZ0+FSEIhMxIJrBnQhMdUvT8OKQ3m4gpRdSa2UXBpjdrycq3gU=,iv:wppcduGlIJG8A+X5qWSd/Xwk2Vswi0ggXfij3bee3xU=,tag:l5zyIxz4tfPV79QB++lWoA==,type:comment]
    #ENC[AES256_GCM,data:cU9T7O8LBMiOTgtFZzROKJs3Ojw3BRM0aVivyesM8WjqnM8GvQPcCA4O5Wk=,iv:aWuvX/Us05RftCPcHTgXOrzzTbmTRgFOCfVEy+Dy5us=,tag:etvDpOU54COKhULQ10HnCw==,type:comment]
    VIP: ENC[AES256_GCM,data:/GYtJ+jq3QVnPuVAfQ==,iv:FL+b7YjhnjlH5Dk40TQKPCAW1ORC4vWi2MQFVG5H5Tc=,tag:jH6W4Jxr7x8Os60LQcO0Pw==,type:str]
    #ENC[AES256_GCM,data:NM5QYDOAKZmwJ53T6yAm+tNoSq4avKPjCTE=,iv:bm/9fq2pc2ZyXhajfEUVsAd8+BXzbzxt76+pCn76FGI=,tag:5Yj0IDXY/py4ZA9myO7a9g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:PuXML8PfCoIlceYIVWk=,iv:jyfu3iD6iEehENStMby3SfFHZZY8cLmzUHzmynV2G/g=,tag:K/r4x1ey9pA0DG9S+ilK4g==,type:str]
    #ENC[AES256_GCM,data:suCQQ5NQ5fZez4JMnXXgqNwMbxtbgY8qs63ZrGen6FusaQ==,iv:8uK4ycoVKFsprNtx6cW1fevPSvv5PT1XkcoGxRntQ58=,tag:BPcXn/6DF97YcOt2OU//LQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:vdVPljM9NYKxFDGn,iv:Bgmkydz2ANBq2c3kLLf7S7CZm27wXRrWwEEHdA0njJ4=,tag:AYO+i+Q42jJUe6mRg0GW4w==,type:str]
    #ENC[AES256_GCM,data:D5RQazx/dBxeyzzL7gsQxgIyUfDj/emXFkj73udce8MaRd9EBR+tizZforWmWUA=,iv:hJgE84BKyCvLi7WiecwYcNihsKGHDfzpuiT2xwSkmOI=,tag:6ELgxoEVBrsgUrQ/nDQX4A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:PFAhnF75Z2EVXI1CmH2JS4oPZqSDOKvN71Qt,iv:547VQQ6nfG76lH8ZmF8iiIW/N1YDxTrxULNWqSOnax8=,tag:4PQhjXPX2KVqFKKcb8S9dg==,type:str]
    #ENC[AES256_GCM,data:V2jr8+Oo+M6TdfxPLG39ntF1oCAWN3Ym87XmUH2zjnQcvjCOqsmc9WQx1UcTXEt69xW14xnZBuoU3Vjt+XKMhlnFAAY6abz+/Lq8haMmFgg=,iv:QTHZiHWwIOt2zfQbf2vcA4C9OLPykMnjakLpQN9MNl8=,tag:bUnrjtLpqT+L74O8BSKg7Q==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:iMqkxwPojVvWfgCyhA==,iv:V3+aAbBaQKHXujPPcHRXwb/Kf0307js5K0cZK61BQu0=,tag:GWPCfXYjwnwVDZ3kO8Y17w==,type:str]
    #ENC[AES256_GCM,data:1Fw4Qph6qJiVamuMLiesV8HVjl+CMYloFihf6+2hRD8PUTe5ABvikt44qEmHLCpSbPAgpRSft58=,iv:+cgW5PwMaRZF0pyj9arAAKonXQP4Dh4Wuj6TKYrgPY8=,tag:l6sAe05rrLi9g2dJPcNKbA==,type:comment]
    #ENC[AES256_GCM,data:SuRdS/MCfvAThYzPoSSypIgpdu/bQN86Rw==,iv:H8OT/eNrLkwI8NEYLTELFghSILUqhd5SRpw4RXvH3i4=,tag:XjnMAYP5E0FBkIxWD1Wl0Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:tOA9vyJ6jOTPeS49ov3YqDxj9toRva5E7qTBlj2o0bqhwr5KZ0S95YNmbFM4nQU=,iv:qB0NwXeOEzua2KIx8ULj/mhtO9UnRJhSbrDbb0Apuno=,tag:U2hIAOuG8FQ0Iivu5szuwQ==,type:str]
    #ENC[AES256_GCM,data:ki+JK61dKj/m5GJ5ol2DzOaK8082iZj+MuF2r+khQIPcXGppM2eICbjhX9u7i0gV11tiT5Y1FWI8rlpqME29mfI3srJFg7w=,iv:cpoIDBNpGpIK+8A6HxtIxTPrZqr8DjqBRirxp5oml3g=,tag:duEpValJNVrj2XB3o25JDQ==,type:comment]
    #ENC[AES256_GCM,data:1SPIzTqGHI9NMUmiWaE3mCqLjEjGTsJ/4/IAT6WeW1zc7JOEXw3oUmKJHT2Jw19jmCXVKqCe,iv:yiXe56q0vnCqBOtXzWybeMEuIbC8ovmvZfdgMIGZtYM=,tag:uKBfUu5JOeyiU01ntFc+1Q==,type:comment]
    #ENC[AES256_GCM,data:GUw0v7FEYnD1EScIBGAJj2+MHGPt8WivZ3K9CPrluoxE+lw=,iv:y8stdtgQghCfMAhwBGNLSFz4hlrFJCNV6bkV1LphoIc=,tag:gU7vmLYA54K/RseUYn/pLg==,type:comment]
    #ENC[AES256_GCM,data:NNXPcTpTh30LtkruINhEWk0kY13/RYlpd+WWOyasc38dmmpLvUS1,iv:L8H26NihSXBZ7SMgZ3TU55BZzRG929obSLI3/c7g8sI=,tag:nFrrc2vhKQBmmdcsb97odw==,type:comment]
    #ENC[AES256_GCM,data:f8tynBOx4EkQ1bAfg48=,iv:40eiMnbE0+NynCq7Qo89EyKum6d1D0McrOiVjZFYhrY=,tag:0XzBv3OcXQeTJv/KP7j+PQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:OIJ3UegAOoOSRRXZIA==,iv:bLrM3As9/34xKyfONVR+gaYwby5SQP+fW+bha4A5S4Y=,tag:dYQ2FgKJCGgQdxZgBojqMw==,type:str]
    SVCNET: ENC[AES256_GCM,data:5DfcGlWMpGVsVIAsrA==,iv:5q6SU9Gr/GgLWEVCN4jt0Kmwc8awNlw3GTAADUps8T0=,tag:XVbBos05TntwRJGkBQ/i/A==,type:str]
    #ENC[AES256_GCM,data:C0sFBfKOtJioYQ==,iv:RTBmqD6To1AD3DZFsHrfl4AS8CoKA/i4TQjrmKUVB+4=,tag:TaW9xOm+rrQYtJxY09totQ==,type:comment]
    #ENC[AES256_GCM,data:L2xjqdshfmQ=,iv:1IoT6LsWjnuI2TTf4xZroRN8YnRUMd3HvnfeCZSGxOQ=,tag:KhkA8G9Xay7y3EjwR+Qwuw==,type:comment]
    #ENC[AES256_GCM,data:KVIswUM8+iLoogf67aa0itUPq7cOxmfy3Q==,iv:1ryNJVxufkmXEFWTLKNY5Yy9z3y2WQlS/3yvplD3X7Y=,tag:0s9XTs4l5KG5zgGjB1IkbA==,type:comment]
    #ENC[AES256_GCM,data:kqq47M1KaQ4cYw==,iv:DdtsrJlyqW7awMDyZdX+JRhj/XqhyBDmwrg4WzeAmQw=,tag:tky0OjA+Gn8tYHbr3OG8jA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:3wX5n4Hw+B6MVojZVg==,iv:GeCLBBKDWMe5fZWMCIYlOCR4qK4b/6at3KRqXREGouQ=,tag:Jn3Kz0szy3BllpSOBA0I3g==,type:str]
    HA_IP: ENC[AES256_GCM,data:kCLsKWXCVS52lS0YfQ==,iv:mx9lttK99CDv7mHz3SvkLav4tmUfRObMdv8/wWXvLu0=,tag:Ab6x+0mqz3lKsrxK7MaFuQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:yu6FLK7v6SWpM/qsAQ==,iv:EAGAnXtrxAHIzmHwzn3RjTowgvuzLzvk4Ucujwcx/Bs=,tag:ABaAgjjZK/i2HTBBD9SJyw==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:pypf6LKR7H61Gynkxl0=,iv:od2xQErhtIhe5T332yd5FJGVZN2oPREm4L441InEIvw=,tag:uGZq2wHOfAIK8rSLxmKNRA==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:xmxtGXxvM4iiwVtcrIY=,iv:+x9/kaSyVNxjdjXwGJvyluN2krtvum2ldwCJayXqFrY=,tag:fFhSuw3Dyjxa7Fnsf7kCjA==,type:str]
    MAIL_IP: ENC[AES256_GCM,data:IaVlXJTtosXbh51aMgc=,iv:i+ELaDxkqvoMTftvM4bpCmlsoYlkCwOsfo4EZAkuzXA=,tag:ohCi0OaKr15kGxP7Ci5P9g==,type:str]
    NEXTCLOUD_IP: ENC[AES256_GCM,data:nofq1nJeuUNZO32VnA==,iv:T+WpSGm+LhNV10Rv9y6+83iKZJ/VOKl70KxQQc+3RCw=,tag:UwEVbm3M9RJWg6Iar72hTg==,type:str]
    HASS_IP: ENC[AES256_GCM,data:6tCe0wssUMT5sdTeEg==,iv:mUiJUtuMBIiWhITIR4TWZ9/qXMRdeHtix0oCuhtGVVA=,tag:tDXMxydK90nzRbP2dp8Xtw==,type:str]
    #ENC[AES256_GCM,data:OeVtNf/L,iv:9XbZH72rxkNnVlO9dT6dDAvgnmnQvALfHw/IbQl1KnU=,tag:/uiIVbL2AXtLl5H5S3Corw==,type:comment]
    EMAIL: ENC[AES256_GCM,data:c8J+wCrs3KZwnlpSKVOP2bqwrSse/sF2eXRazeIUMA==,iv:7VdzbKu5A35lHjqkdKaCz56aPJ4dqHoA8Pc8+UblW+8=,tag:YHqD17XPUKmYuMEUM8jmbA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:wzYS/EUYepuCBZBRDUPEIBoK32wG9paTQyD/5XE/w/SBoyqa0A9ZYA==,iv:bxGvaXRs+xMk2nNM8e5+pw/4G3JKjXnLeU3qs+TxlsM=,tag:TeETIpnRy6W16Phsqnukhw==,type:str]
    S3URL: ENC[AES256_GCM,data:GeIFfXSIN4v2Vte9VTOmCoujoSQs+KKYlkOnPbbV,iv:FFyJ08uUk/8TAkazIVBdCdxin/5+uWPJa/2tSZeR3Hk=,tag:EwBocC9ztcLUb1LZdPMu+A==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:C25k7e4SC+QZ2oIdzw==,iv:K2urBGrC+uRMCNILSu+X55RoHlgDIGwPrRei3pP6n0o=,tag:u9A3v+QYzl1nY5hx38wMrg==,type:str]
    S3ID: ENC[AES256_GCM,data:56EWZ1ZXhBSihO1f,iv:zLC+y5woKN9zM6rRqjTgFNrF+D6fWYJ5qFy/0hz9hXI=,tag:cn7OxHVbQJ/ZYI7kanKwew==,type:str]
    S3KEY: ENC[AES256_GCM,data:g2Y5jO/fD5vSqbjnhr1/cf2xf7R6l2pepf/xtYGkx/i4dnEKxzfCvnGN,iv:EvDQ083iPeY1PoTUR9tJCWUoNPQps8c36ZOzvaUGIuc=,tag:SQqc8bnyiMIHHnwFo2120w==,type:str]
    #ENC[AES256_GCM,data:tfPTukKoxvE=,iv:+BfwBlmpe9y6e34GoydHmNukFVRj71bLb1ipzJygQrI=,tag:DP8VuhQ4FOqxWnp6T32gOQ==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:RLtLJDfFofmA7xEa/g==,iv:xkckNxBaZ+ixrhSZ5Oq9Biq2lyq2KeVzqHGEPoGHKWw=,tag:6FoDX4Ksik1fQA2gZMv7mw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:P5CUPw==,iv:Z7cG70i8QqlMvlvnOW/7+u3EIpvihl6ki/tiKEDtGLk=,tag:vamkavynrKUbOg7Mt49RVw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s36l3k7xz668jyqa6200me5tx7xg2nzs0ew6rzp05cjnmvl6kpqscc2frq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRGRtaEZWNk9LbkVoTmRP
            UVJZWVpOeGhTbHVVczk1OGI5MUdQM3NyK0I4CmVSaVJjNVU4QVhUNytoT2FpaHVP
            VVFqOWRJYVRpUVA2T2VSYjJKcXZ0WjgKLS0tIFlIK3BwS0NiWHVuT3FKQkdVRFpN
            VGRKZ3Z4dnhhYWR3c0w5ZlpzcDNlbk0KmPFhDqP0jpw4oLgMeGByCha5q0jdY96n
            c9UbD8f4yWg47mz2PD1N6knTfp5toGMnDBmj62C3H6o0DInsO3+NIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T22:50:07Z"
    mac: ENC[AES256_GCM,data:Gp5iwMZeJBi5TyMI0/mT1TYd0rqH1bs3df2WmRNuMu9vgHooUcWYcy7sy/2r10Vgx+bVeOCP3BtQ7BblAoaT0u6DZS2JcvYxNByekBvwt8SxzGmJLbcdbfZdL8L04OKetcH6K5b9I830jnKRMHVPfOmZu/DhScd34UaXRsXmJVg=,iv:G4PS6MdysAIb9jEBxA0o/Ta8T/2gIPNkuF4bbQ1BF/I=,tag:KqFUWo631RhD47AoCKJeBA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
