apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5Inxv8g33CfahRi9N7Xj29a0eZ8XZwc1tks2gkwmKy6hPWNRa6pcAtHu9aME+bZlcH8o1Z0oxULEzY/GIztwQbnx1apjuy0brBlGDIKtAfc2eB1MOtpz0XR5TXj6bTqIFIC9yHq/mbVf4qou53f312qvt44Jq/UB6kO+iRCLVMbVCfjcp0sbFeCL3jM0X1/76ZGAQyvy+Yk0iVCYvsYdin/f3nuJRxKlU6NNB4hqsdoaZpP/958avLNoSM+urtUXo/2PIex+7fGlXg6Qvleud4nyVLYQph3fcHsAfSDD6SF9q0OJO+BQ5cQglBKRLxFwyjY9jHR18MM+ovcH3TbhX8wa8/2OkuWEYW29G4iWzEZ6cVfMaUV/KcacyZ5cC4N/,iv:lv2zao12GHRyOQqIDPtB+EcHTsnQDOl1Bpz3Y5qkWn0=,tag:L3iIn+9/boBgwb+apiByiA==,type:str]
    identity.pub: ENC[AES256_GCM,data:nBu8cmkP1GGkFWCn+yfidxUlmgln25oADl1omUH0uDM+JIqJ6BT3zg2fnqYqpMWetHS+HEdDA5Nga5tTEAGAdtgTGPV15YIklUpBDHrkc0TNyZEp1BbHwyEYltpEy7qvGb9t/3+yrKuxn07SmDKcintHF3y94JCKLWfBCWXZvqK5IyQUBeuHTsMKGfd+rsJyNwo0DE87xWV3fYYgU8lU3Sw6Vf1fJtYhVnd/kxLo4PZ3kLbW6xh3BLGQTSEo91nP5S1NHX9ZhQLBlderng==,iv:uLr9wXJtYuYa46kzN3ugxSq8rIHgXm0cgVJJArNQZTg=,tag:qHHK8wb/NVd+8PJVSuUV8Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:eb/RW7M4+O7LFx1OdPpRSZ2LQQtRfUhvgyExbEDca9izEX3aJALcisV0B63+FtprFPOKnjJfr6gd2cMSfp525HP+3dFFoCIaovx7XiHYDfmODfzF6yK5oC0f5aFRR7ktGiHqN4RxpQ7+AYU5GUiY+R/hO9DJFo6sT710K4bXk0hqzRBk11Hvt2vdGZf8YcdidZxIyqoOp5y//ZQ9MwjFPHkUo2cBkvsAHLvQ,iv:L+E5qQZNYUMz99GlAASzZyby7SI62AYgndmO4TKHgEk=,tag:Lz+zUGZD93Lr9PREVw6uUA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s36l3k7xz668jyqa6200me5tx7xg2nzs0ew6rzp05cjnmvl6kpqscc2frq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV2UrUnBmQUFmOXFZeDQ4
            ajhDY29QUTMxT2ZIajczR2RZeXFaNldpT3pzCnZMTmhQZUR2dHhCa0w0cVByNk1M
            WlVRSGR1MERMbm1LYkE2Qm5pRFlkNUkKLS0tIEtLbUlyR25LQ3JKMmlUMkxlR0J1
            QjczWSthZ3kzbEhid0ZISENWb0o5QVUKY7sm1cJpw07qpMVsDLPj8HKolKQmypyG
            Sc6IxadiGyo/Z7A4e/AsT0fI0C9sCKfZufV17ccJTvswC8VyaWr72w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T22:50:07Z"
    mac: ENC[AES256_GCM,data:MXq3i3np9T6ZxJ0/KPKo4Va+WlVDz+wBNabLhYhumtqyPSmN/KaEIXSK4tl3AzSKsB605Vd3dXK3uKAs7eZsX0kgPqONk6wlOgm5O1Oevdjg/R8BERGb0lq46pAg3ZBNtucJS1OOTLnH2t9ioFD9Xmvw+0wJGeJoo/ehPCCjY3E=,iv:FH/cs1brrlttPxhw7m1J1dpEswvyMG74buJYG6cjVd4=,tag:p1cmk4JYbCKvc9cSXEs61Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
