apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aDJx5JLVpTlEPpnClsFHK+1rqrkFPD9M/4lKLvsll5+gUvUsfVfipNh0b/60UEt/u3KD+TvBElXuPlsRgPkGD3y6hGIn3xTnSzLIrtaWelP1Lm7x25gQLiIBGZ+2vayMPxKJ8YOiekHpRMR4giaXcQlsSBK0W9S7cPIyI4l/BzQz0gjRh+xGuDiNoIlt5rGEq7JlibuW3eDg4TtDfhU1nAX05zMOYKEkfthhNwNysnqzk9b9mf4bqlTcPMvfwlrxvPIgFm5dscRXW2ce9m6zrHiyA+/k005XC16bxZ1JpqtexfABgvfYFt6xXZ+lCdffpaRtA1aX038t+/t7qr8Mg5jWM5nVpAyvWF1JpEN9WUl5EFpFtvLFd6VWlw8xYfoW,iv:LI8ansT8UIZarDQaX9uh7kjfRoyWV518hVQ0m7BQdjI=,tag:f9K9CRkasHpFhutxPVNCKQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:nBm7gg4j7FkTbueZb28WmO+Z/1fie0kE4RWIJhSoTf9pffS/aG2FGn9yXR9Bi6ffVehorQ6T5F0JZAcVrsQmpdxnP3PaEnaNEtfFMF8dFWRB+eSBtu45gd1katGx6qcbLS+9N72s1mmgXZe5PX08fxN8UluckKy7L7vX/N4rW/xMP6Lmu4yEG6oRFPwWsX9duJJwe3hXLZkpZlU1eMnyI/fA77Vz2QKhTNVORqOlrjZYfzZIx+E5TD137JUazdEJI/O6VjsCI4dB7uN0PA==,iv:IopxlXeYmGmi2Wh0PxcMXyIpCDr7z7QbXl0nrcXErX4=,tag:76vRwQPswfu9HQJBbjk8tQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:lhULF8cw38PsvehxPpddMHp209VbBZN7i0fVSssBR0HeYMNXz2qfEFQ2ApxpB73paOLVqpXv0KiZoXtpZTXFtuwCiFz8S7iGHsS0iPbJf0JGvUBpk8vco2S33qbxYZaAPt9Pk+GrpCegtb6Fw50ILM0iX9MQZpu53GNJ5TEm53+g7WvVwz4Nth7vQlobrtheXvnFmbCYWPpJkaBod+ZQkqgKk99abYSsVwxE,iv:TxbOVzIrZnbarW8FoOiP1z5vgL9GFbO1kKxAxMOxtrk=,tag:+dtnEz4VWkMqM8QxBT8z6w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s36l3k7xz668jyqa6200me5tx7xg2nzs0ew6rzp05cjnmvl6kpqscc2frq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0V09pa3RNMEY5OGUxN1B0
            aXZjbzdvR2ZsaW5qYjBWbWMyb2RLSFhyRlh3Cnk3bFFIbWIrQS9JZm9PU3FkeWNM
            WlQxbHdCWGJab25OWGd6Uis5Y1R5K3cKLS0tIGs3WDhNWEdFWkx3ay9OK05maUNH
            c0I1TEVlaXhtT2Ura1g3WFlvaHplSXcKLXu/NMS5Ero0Rcsh40jraCT+U/SLVeoP
            KLr4F0Hr7xdBfC2KW+pu+8IJxYlhvHXfwkv00HHwz3nTLm5KQJhnCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T19:18:58Z"
    mac: ENC[AES256_GCM,data:09QnNv3L1rgvja/qoypc7a1m50Et8hZd+LQsH4StFBB4pzfaKpQvdWPN13qitX/8i7sHau7mhZDQAX3106mS4pCDXhl0ckBMPcqEqoD8mDvtr0ioWHKTNPeeUfBE+KMk3UiqRHey1G6o34D5oEPs4lf2Tl4V2xRAUKIWs2d5+xE=,iv:C1bGfMWWcQOJivZzWfpi/mgX9xP5v4UlbnLuC7gjVc0=,tag:HG5s+Kma6UO4p66IJzCa2g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
